// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLVfLxlN25zAMwoYUk8eYT9jcaF5ZcZzo',
    appId: '1:206829795173:web:9b8675c602faf5e384138c',
    messagingSenderId: '206829795173',
    projectId: 'fcg-app-v1-aa4fe',
    authDomain: 'fcg-app-v1-aa4fe.firebaseapp.com',
    storageBucket: 'fcg-app-v1-aa4fe.appspot.com',
    measurementId: 'G-XLBJY5H05F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBSo4I6WjQBBcWi_3vLKLmYGk6lTJF5OQ',
    appId: '1:206829795173:android:0309758099c128ef84138c',
    messagingSenderId: '206829795173',
    projectId: 'fcg-app-v1-aa4fe',
    storageBucket: 'fcg-app-v1-aa4fe.appspot.com',
  );
}
